ats/atsproject/atsapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='indexats'),
    path('babyregistration/', views.baby_registration, name='babyregistrationats'),
    path('deletbabies/<int:baby_id>', views.deletbabies, name='deletbabies'), 
    path('editbabies/<int:baby_id>/', views.editbabies, name='editbabies'),
    path('home/', views.home, name='home'),
    # path('<int:year>/<str:month>/<str:day>/', views.home, name='home'),
    path('<int:year>/<str:month>/', views.home, name='home'),
    path('sitterstatus/', views.sitter_presence, name='sitterstatusats'),
    path('babycheckin/', views.baby_checkin, name='babycheckin'),
    path('babycheckout/', views.baby_checkout, name='babycheckout'),
    path('babylist/', views.babyrecords, name='babylist'),
    path('bcheckinrecord/', views.bcheckin_list, name='bcheckinrecord'),
    path('edit_checkin/<int:checkin_id>/', views.edit_checkin, name='edit_checkin'),
    path('delete_checkin/<int:checkin_id>/', views.delete_checkin, name='delete_checkin'),
    path('bcheckoutrecord/', views.bcheckout_list, name='bcheckoutrecord'),
    path('edit_checkout/<int:checkout_id>/', views.edit_checkout, name='edit_checkout'),
    path('delete_checkout/<int:checkout_id>/', views.delete_checkout, name='delete_checkout'),
    path('editinfo/', views.edit, name='editinfoats'),
    path('financereport/', views.finance_report, name='financereport'),
    path('inventory/', views.inventorylist, name='inventory'),
    path('edit_inventory/<int:inventory_id>/', views.edit_inventory, name='edit_inventory'),
    path('delete_inventory/<int:inventory_id>/', views.delete_inventory, name='delete_inventory'), 
    path('login/', views.login_user, name='login'),
    # path('signup/', views.signup, name='signupats'),
    path('purchaseorder/', views.enterpurchase, name='purchaseorder'),
    path('salesorder/', views.entersale, name='salesorderats'),
    path('salesreport/', views.productsaleslist, name='salesreport'),
    path('edit_sales/<int:sales_id>/', views.edit_sales, name='edit_sales'),
    path('delete_sales/<int:sales_id>/', views.delete_sales, name='delete_sales'),
    path('sitterlist/', views.sitterrecords, name='sitterlist'),
    path('sitterregistration/', views.sitter_registration, name='sitterregistrationats'),
    path('editsitters/<int:sitter_id>/', views.editsitters, name='editsitters'),
    path('deletesitters/<int:sitter_id>/', views.deletesitters, name='deletesitters'), 
    path('dashboard/', views.general_counts_view, name='dashboard'),
    # path('search/', views.searchbabies, name='search'),
    path('logout/', views.logout_user, name='logout'),
    
]

    # home
    # babycheckin
    # babycheckout
    # babylist
    # babyregistration
    # bcheckinrecord
    # bcheckoutrecord
    # editinfo
    # financereport
    # inventory
    # login
    # purchaseorder
    # salesorder
    # salesreport
    # sitterlist
    # sitterregistration
    # summary

ats/atsproject/atsproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('atsapp.urls')),
    path('home/', include('atsapp.urls')),
    path('sitterstatus/', include('atsapp.urls')),
    path('babycheckin/', include('atsapp.urls')),
    path('babycheckout/', include('atsapp.urls')),
    path('babylist/', include('atsapp.urls')),
    path('babyregistration/', include('atsapp.urls')),
    path('bcheckinrecord/', include('atsapp.urls')),
    path('bcheckoutrecord/', include('atsapp.urls')),
    path('editinfo/', include('atsapp.urls')),
    path('financereport/', include('atsapp.urls')),
    path('inventory/', include('atsapp.urls')),
    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('atsapp.urls')),
    path('purchaseorder/', include('atsapp.urls')),
    path('salesorder/', include('atsapp.urls')),
    path('salesreport/', include('atsapp.urls')),
    path('sitterlist/', include('atsapp.urls')),
    path('sitterregistration/', include('atsapp.urls')),
    path('dashboard/', include('atsapp.urls')),
  
]

ats/atsproject/atsapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.core import validators
from django.db.models import Sum


class Baby_Register(models.Model):
    babiz_sur_name = models.CharField(max_length=20)
    babiz_other_names = models.CharField(max_length=20)
    babiz_gender = models.CharField(max_length=20, choices=[('Male', 'Male'), ('Female', 'Female')])
    babiz_date_of_birth = models.DateField()
    parentz_sur_name = models.CharField(max_length=20)
    parentz_other_names = models.CharField(max_length=20)
    parentz_gender = models.CharField(max_length=20, choices=[('Male', 'Male'), ('Female', 'Female')])
    parentz_date_of_birth = models.DateField()
    parentz_telephone = models.IntegerField()
    parentz_address = models.CharField(max_length=50)
    parentz_email = models.EmailField(max_length=50)

    def __str__(self):
        return self.babiz_sur_name


class Sitter_Register(models.Model): 
    sit_sur_name = models.CharField(max_length=20)
    sit_other_names = models.CharField(max_length=20)
    sit_gender = models.CharField(max_length=20, choices=[('Male', 'Male'), ('Female', 'Female')])
    sit_date_of_birth = models.DateField()
    sit_nin_number = models.CharField(max_length=20)
    sit_educlevel = models.CharField(max_length=20, choices=[('Primary', 'Primary'), ('O-Level', 'O-Level'), ('A-Level', 'A-Level'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Others', 'Others')])
    sit_religion = models.CharField(max_length=20, choices=[('Born Aagain', 'Born Aagain'), ('Anglican', 'Anglican'), ('Catholic', 'Catholic'), ('Islam', 'Islam'), ('Others', 'Others')])
    sit_address = models.CharField(max_length=20, choices=[('Kabalagala', 'Kabalagala'), ('Other', 'Other')])
    sit_email = models.EmailField(max_length=50)
    sit_telephone = models.IntegerField()
    snok_sur_name = models.CharField(max_length=20)
    snok_other_names = models.CharField(max_length=10)
    snok_gender = models.CharField(max_length=20, choices=[('Male', 'Male'), ('Female', 'Female')])
    snok_date_of_birth = models.DateField()
    snok_address = models.CharField(max_length=50)
    snok_email = models.EmailField(max_length=50)
    snok_telephone = models.IntegerField()

    def __str__(self):
        return self.sit_sur_name
 


class Sitter_Status(models.Model):
    sitter_id = models.ForeignKey(Sitter_Register, on_delete=models.CASCADE)
    sitter_availability = models.CharField(max_length=10, choices=[('On Duty', 'On Duty'), ('Off Duty', 'Off Duty')])
    sitter_time = models.TimeField()
    sitter_date = models.DateField()
    def __int__(self):
        return f"{self.sitter_id} - {self.sitter_availability}"

class Checkin(models.Model): 
    baby_id = models.ForeignKey(Baby_Register, on_delete=models.CASCADE)
    checkin_time = models.TimeField()
    checkin_date = models.DateField()
    checkin_care_time = models.CharField(max_length=10, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')])
    checkin_guardians_sur_name = models.CharField(max_length=100)
    checkin_guardians_other_names = models.CharField(max_length=200)
    checkin_guardians_telephone = models.IntegerField()
    sitter_id = models.ForeignKey(Sitter_Register, on_delete=models.CASCADE)
    checkin_payment_choice = models.CharField(max_length=10, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')])
    daystar_checkin_fee = models.IntegerField()
    daystar_checkin_fee_currency = models.CharField(max_length= 10, choices=[('UGX', 'UGX'), ('USD', 'USD')], default= 'UGX')
    checkin_comment = models.CharField(max_length=1000)

    def __int__(self):
        return self.baby_id
    

class Checkout(models.Model): 
    baby_id = models.ForeignKey(Baby_Register, on_delete=models.CASCADE)
    checkout_time = models.TimeField()
    checkout_date = models.DateField()
    checkout_care_time = models.CharField(max_length=10, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night'),])
    checkout_guardians_sur_name = models.CharField(max_length=100)
    checkout_guardians_other_names = models.CharField(max_length=200)
    checkout_guardians_telephone = models.IntegerField()
    sitter_id = models.ForeignKey(Sitter_Register, on_delete=models.CASCADE)
    checkout_payment_choice = models.CharField(max_length=10, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'),])
    daystar_care_time_fee = models.IntegerField()
    daystar_care_time_fee_currency = models.CharField(max_length= 10, choices=[('UGX', 'UGX'), ('USD', 'USD')], default= 'UGX')
    checkout_sitter_fee = models.IntegerField()
    checkout_sitter_fee_currency = models.CharField(max_length= 10, choices=[('UGX', 'UGX'), ('USD', 'USD')], default= 'UGX')
    checkout_comment = models.CharField(max_length=1000)

    def __int__(self):
        return self.baby_id 

# class Procurement(models.Model):
#     po_item_number = models.CharField(max_length=20)
#     po_product_name = models.CharField(max_length=50)
#     po_unit_cost = models.IntegerField()
#     po_purchase_date = models.DateTimeField()
#     po_entry_date = models.DateTimeField()
#     po_quantity = models.PositiveSmallIntegerField()
#     po_total_amount = models.IntegerField()

#     def __int__(self):
#         return self.po_item_number 


# class Sales_Order(models.Model):
#     so_baby_id = models.ForeignKey(Baby_Register, on_delete=models.CASCADE)
#     so_date_created = models.DateTimeField()
#     so_item_number = models.ForeignKey(Procurement, on_delete=models.CASCADE)
#     so_unit_price = models.IntegerField()
#     so_quantity = models.PositiveSmallIntegerField()
#     so_total_amount = models.IntegerField()

#     def __str__(self):
#         return f'{self.so_quantity} x {self.so_item_number.po_item_number}'
# def doll_total_quantity():
#     total_quantity_of_dolls = Purchase.objects.aggregate(total_quantity_of_dolls=Sum('po_quantity'))['total_quantity_of_dolls']
#     return total_quantity_of_dolls if total_quantity_of_dolls else 0

class Purchase(models.Model):
    po_item_number = models.CharField(max_length=20)
    po_product_name = models.CharField(max_length=50)
    po_unit_cost = models.IntegerField()
    po_purchase_date = models.DateTimeField()
    po_entry_date = models.DateTimeField()
    po_quantity = models.PositiveSmallIntegerField()

    @property
    def total(self):
        return self.po_unit_cost*self.po_quantity

    def __str__(self):
        return self.po_item_number

    @classmethod
    def purchase_total_quantity(cls):
        return cls.objects.aggregate(purchase_total_quantity=Sum('po_quantity'))['purchase_total_quantity']
    

class Sales(models.Model):
    so_baby_id = models.ForeignKey(Baby_Register, on_delete=models.CASCADE)
    so_date_created = models.DateTimeField()
    so_item_number = models.ForeignKey(Purchase, on_delete=models.CASCADE)
    so_unit_price = models.IntegerField()
    so_quantity = models.PositiveSmallIntegerField()
    @property
    def total(self):
        return self.so_unit_price*self.so_quantity

    def __str__(self):
        return f'{self.so_quantity} x {self.so_item_number.po_item_number}'


    
    
    
    
    
    
    
    
    
    


   

ats/atsproject/atsapp/templates/atsapp/babycheckin.html
{% extends 'atsapp/base.html' %} 
{% load static %}

 
{% block content %}

<div class="">
  <br>
  <h4 class="h4heading text-center">Checkin Baby Here</h4>
  {% if submitted %}

    Baby Checkin Was Successful!

  {% else %}

    <form class="" action="" method="POST">
  
      {% csrf_token %}
  
      <div class="form-container p-3" style="width: 70%; margin-left: 15%; border-radius: 20px; background-color: rgb(238,242,255);">
        <div class="form-column">
          <label for="id_baby_id">Baby ID Number</label><br>
          {{ form.baby_id }}<br>
  
          <label for="id_checkin_time">Checkin Time</label><br>
          {{ form.checkin_time }}<br>
          
          <label for="id_checkin_date">Checkin Date</label><br>
          {{ form.checkin_date }}<br>
          
          <label for="id_checkin_care_time">Care Time</label><br>
          {{ form.checkin_care_time }}<br>
          
          <label for="id_checkin_guardians_sur_name">Guardians Surname</label><br>
          {{ form.checkin_guardians_sur_name }}<br>
          
          <label for="id_checkin_guardians_other_names">Guardians Other Names</label><br>
          {{ form.checkin_guardians_other_names }}<br>
  
          <label for="id_checkin_guardians_telephone">Guardians Telephone</label><br>
          {{ form.checkin_guardians_telephone }}<br>
          
        </div>
  
      
  
        <div class="form-column">
    
      
          <label for="id_checkin_payment_choice">Payment Choice</label><br>
          {{ form.checkin_payment_choice }}<br>
      
          <label for="id_sitter_id">Sitter ID Number</label><br>
          {{ form.sitter_id }}<br>
      
          <label for="id_daystar_checkin_fee">Daystar Checkin Fee</label><br>
          {{ form.daystar_checkin_fee }}<br>
      
          <label for="id_daystar_checkin_fee_currency">Daystar Checkin Fee Currency</label><br>
          {{ form.daystar_checkin_fee_currency }}<br>
  
          <label for="id_checkin_comment">Daystar Checkin Fee Currency</label><br>
          {{ form.checkin_comment }}<br>
      
  
        </div>
        
    </div>
    <input type="submit" value="Submit" class="btn btn-light mt-3" style="margin-left: 40%; width: 20%;">
    </form>
    
  

</div>

</div>




 
  {% endif %}
  
{% endblock %} 

ats/atsproject/atsapp/templates/atsapp/babycheckout.html
{% extends 'atsapp/base.html' %} 
{% load static %}

 
{% block content %}

<div class="">
  <br>
  <h4 class="h4heading text-center">Checkout Baby Here</h4>
  {% if submitted %}

    Baby Checkout Was Successful!

  {% else %}

    
    
      <form class="" action="" method="POST">
    
        {% csrf_token %}
    
        <div class="form-container p-3" style="width: 70%; margin-left: 15%; border-radius: 20px; background-color: rgb(238,242,255);">
          <div class="form-column">
            <label for="id_baby_id">Baby ID Number</label><br>
            {{ form.baby_id }}<br>
            
            <label for="id_checkout_time">Checkout Time</label><br>
            {{ form.checkout_time }}<br>
            
            <label for="id_checkout_date">Checkout Date</label><br>
            {{ form.checkout_date }}<br>
            
            <label for="id_checkout_care_time">Care Time</label><br>
            {{ form.checkout_care_time }}<br>
            
            <label for="id_checkout_guardians_sur_name">Guardians Surname</label><br>
            {{ form.checkout_guardians_sur_name }}<br>
            
            <label for="id_checkout_guardians_other_names">Guardians Other Names</label><br>
            {{ form.checkout_guardians_other_names }}<br>
    
            <label for="id_checkout_guardians_telephone">Guardians Telephone</label><br>
            {{ form.checkout_guardians_telephone }}<br>
    
            <label for="id_checkout_payment_choice">Payment Choice</label><br>
            {{ form.checkout_payment_choice }}<br>
            
          </div>
    
        
        
    
          <div class="form-column">
        
            <label for="id_sitter_id">Sitter ID Number</label><br>
            {{ form.sitter_id }}<br>
    
            <label for="id_daystar_care_time_fee">Daystar Care Time Fee</label><br>
            {{ form.daystar_care_time_fee }}<br>
        
            <label for="id_daystar_care_time_fee_currency">Daystar Care Time Fee Currency</label><br>
            {{ form.daystar_care_time_fee_currency }}<br>
        
            <label for="id_checkout_sitter_fee">Checkout Sitter Fee</label><br>
            {{ form.checkout_sitter_fee }}<br>
    
            <label for="id_checkout_sitter_fee_currency">Checkout Sitter Fee Currency</label><br>
            {{ form.checkout_sitter_fee_currency }}<br>
    
            <label for="id_checkout_comment">Daystar checkout Fee Currency</label><br>
            {{ form.checkout_comment }}<br>
        
    
          </div>
          
      </div>
      <input type="submit" value="Submit" class="btn btn-light mt-3 mb-5" style="margin-left: 40%; width: 20%;">
      </form> 
      
    
      {% endif %}
    </div>

</div>

</div>





  
{% endblock %} 

ats/atsproject/atsapp/templates/atsapp/editinfo.html
{% extends 'atsapp/base.html' %} 
{% load static %}

 
{% block content %}

<br>

<form class="" action="" method="POST">
  {% csrf_token %}

  <h4 class="h4heading">Edit Baby List</h4>
  <div class="form-container p-3" style="width: 70%; margin-left: 15%; border-radius: 20px; background-color: rgb(238,242,255);">
    <div class="form-column">
      <label for="id_babiz_sur_name">Baby Surname</label><br>
      {{ form.babiz_sur_name }}<br>
      
      <label for="id_babiz_other_names">Baby Other Names</label><br>
      {{ form.babiz_other_names }}<br>

      <label for="id_babiz_gender">Baby Gender</label><br>
      {{ form.babiz_gender }}<br>
      
      <label for="id_babiz_date_of_birth">Baby Date of Birth</label><br>
      {{ form.babiz_date_of_birth }}<br>
      
      <label for="id_parentz_sur_name">Parent Surname</label><br>
      {{ form.parentz_sur_name }}<br>
      
      <label for="id_parentz_other_names">Parent Other Names</label><br>
      {{ form.parentz_other_names }}<br>
    </div>

    <div class="form-column">
      <label for="id_babiz_sur_name">Parent Gender</label><br>
      {{ form.parentz_gender }}<br>
  
      <label for="id_babiz_other_names">Parent Date of Birth</label><br>
      {{ form.parentz_date_of_birth }}<br>
  
      <label for="id_babiz_gender">Parent Date of Birth</label><br>
      {{ form.parentz_telephone }}<br>
  
      <label for="id_babiz_date_of_birth">Parent Telephone</label><br>
      {{ form.parentz_address }}<br>
  
      <label for="id_parentz_sur_name">Parent Location</label><br>
      {{ form.parentz_email }}<br>

    </div>
    
</div>
<input type="submit" value="Submit" class="btn btn-light mt-3" style="margin-left: 40%; width: 20%;" value="update task"><br><br><br>
<center>
  <button onclick="location.href= /babylist/" class="btn btn-secondary">Back To Baby Registration List</button>
</center>
</form>
<br>

<h4 class="h4heading">Edit Sitter List</h4>
<form class="" action="" method="POST">

  {% csrf_token %}

  <div class="form-container p-3" style="width: 70%; margin-left: 15%; border-radius: 20px; background-color: rgb(238,242,255);">
    <div class="form-column">
      <label for="id_sit_sur_name">Sitter Surname</label><br>
      {{ form.sit_sur_name }}<br>
      
      <label for="id_sit_other_names">Sitter Other Names</label><br>
      {{ form.sit_other_names }}<br>

      <label for="id_sit_gender">Sitter Gender</label><br>
      {{ form.sit_gender }}<br>
      
      <label for="id_sit_date_of_birth">Sitter Date of Birth</label><br>
      {{ form.sit_date_of_birth }}<br>
      
      <label for="id_sit_nin_number">NIN Number</label><br>
      {{ form.sit_nin_number }}<br>
      
      <label for="id_sit_educlevel">Education Level</label><br>
      {{ form.sit_educlevel }}<br>
      
      <label for="id_sit_religion">Sitter Religion</label><br>
      {{ form.sit_religion }}<br>
      
      <label for="id_sit_address">Sitter Address</label><br>
      {{ form.sit_address }}<br>
      
      <label for="id_sit_email">Sitter Email</label><br>
      {{ form.sit_email }}<br>
    </div>

    <div class="form-column">
      <label for="id_sit_telephone">Sitter Telephone</label><br>
      {{ form.sit_telephone }}<br>
  
      <label for="id_snok_sur_name">Next Of Kin Surname</label><br>
      {{ form.snok_sur_name }}<br>
  
      <label for="id_snok_other_names">Next Of Kin Other Names</label><br>
      {{ form.snok_other_names }}<br>
  
      <label for="id_snok_gender">Next Of Kin Gender</label><br>
      {{ form.snok_gender }}<br>
  
      <label for="id_snok_date_of_birth">Next Of Kin Date of Birth</label><br>
      {{ form.snok_date_of_birth }}<br>
      <label for="id_snok_address">Next Of Kin Address</label><br>
      {{ form.snok_address }}<br>
  
      <label for="id_snok_email">Next Of Kin Email</label><br>
      {{ form.snok_email }}<br>
  
      <label for="id_snok_telephone">Next Of Kin Telephone</label><br>
      {{ form.snok_telephone }}<br>

    </div>
    
</div>
<input type="submit" value="Submit" class="btn btn-light mt-3" style="margin-left: 40%; width: 20%;">
</form>
<br>
<h4 class="mheading">Edit Inventory List</h4>

<div class="daycare_forms row g-3">

  <form class="" action="" method="POST">
    {% csrf_token %}
    
      {{ formp.as_p }}
   
      <input type="submit" value="Submit" class="btn btn-secondary" style="margin-left: 40%; width: 25%; border-radius: 20px; background-color:rgb(21, 105, 111)">
  </form>

</div>

<br>

<h4 class="h4heading">Edit Baby Checkin List</h4>
<form class="" action="" method="POST">

  {% csrf_token %}

  <div class="form-container p-3" style="width: 70%; margin-left: 15%; border-radius: 20px; background-color: rgb(238,242,255);">
      <div class="form-column">
      <label for="id_baby_id">Baby ID Number</label><br>
          {{ form.baby_id }}<br>
  
          <label for="id_checkin_time">Checkin Time</label><br>
          {{ form.checkin_time }}<br>
          
          <label for="id_checkin_date">Checkin Date</label><br>
          {{ form.checkin_date }}<br>
          
          <label for="id_checkin_care_time">Care Time</label><br>
          {{ form.checkin_care_time }}<br>
          
          <label for="id_checkin_guardians_sur_name">Guardians Surname</label><br>
          {{ form.checkin_guardians_sur_name }}<br>
          
          <label for="id_checkin_guardians_other_names">Guardians Other Names</label><br>
          {{ form.checkin_guardians_other_names }}<br>
  
          <label for="id_checkin_guardians_telephone">Guardians Telephone</label><br>
          {{ form.checkin_guardians_telephone }}<br>
          
        </div>
  
        <div class="form-column">
    
          <label for="id_checkin_payment_choice">Payment Choice</label><br>
          {{ form.checkin_payment_choice }}<br>
      
          <label for="id_sitter_id">Sitter ID Number</label><br>
          {{ form.sitter_id }}<br>
      
          <label for="id_daystar_checkin_fee">Daystar Checkin Fee</label><br>
          {{ form.daystar_checkin_fee }}<br>
      
          <label for="id_daystar_checkin_fee_currency">Daystar Checkin Fee Currency</label><br>
          {{ form.daystar_checkin_fee_currency }}<br>
  
          <label for="id_checkin_comment">Daystar Checkin Fee Currency</label><br>
          {{ form.checkin_comment }}<br>
        </div>
    
  </div>
<input type="submit" value="Submit" class="btn btn-light mb-5 mt-3" style="margin-left: 40%; width: 20%;">
</form>
<br>



<h4 class="h4heading">Edit Baby Checkout List</h4>
<form class="" action="" method="POST">

  {% csrf_token %}

  <div class="form-container p-3" style="width: 70%; margin-left: 15%; border-radius: 20px; background-color: rgb(238,242,255);">
      <div class="form-column">
        <label for="id_baby_id">Baby ID Number</label><br>
        {{ form.baby_id }}<br>
        
        <label for="id_checkout_time">Checkout Time</label><br>
        {{ form.checkout_time }}<br>
        
        <label for="id_checkout_date">Checkout Date</label><br>
        {{ form.checkout_date }}<br>
        
        <label for="id_checkout_care_time">Care Time</label><br>
        {{ form.checkout_care_time }}<br>
        
        <label for="id_checkout_guardians_sur_name">Guardians Surname</label><br>
        {{ form.checkout_guardians_sur_name }}<br>
        
        <label for="id_checkout_guardians_other_names">Guardians Other Names</label><br>
        {{ form.checkout_guardians_other_names }}<br>

        <label for="id_checkout_guardians_telephone">Guardians Telephone</label><br>
        {{ form.checkout_guardians_telephone }}<br>

        <label for="id_checkout_payment_choice">Payment Choice</label><br>
        {{ form.checkout_payment_choice }}<br>
        
      </div>

    
    

      <div class="form-column">
    
        <label for="id_sitter_id">Sitter ID Number</label><br>
        {{ form.sitter_id }}<br>

        <label for="id_daystar_care_time_fee">Daystar Care Time Fee</label><br>
        {{ form.daystar_care_time_fee }}<br>
    
        <label for="id_daystar_care_time_fee_currency">Daystar Care Time Fee Currency</label><br>
        {{ form.daystar_care_time_fee_currency }}<br>
    
        <label for="id_checkout_sitter_fee">Checkout Sitter Fee</label><br>
        {{ form.checkout_sitter_fee }}<br>

        <label for="id_checkout_sitter_fee_currency">Checkout Sitter Fee Currency</label><br>
        {{ form.checkout_sitter_fee_currency }}<br>

        <label for="id_checkout_comment">Daystar checkout Fee Currency</label><br>
        {{ form.checkout_comment }}<br>
    
    
  </div>
  </div>
  <input type="submit" value="Submit" class="btn btn-secondary mt-3 mb-5" style="margin-left: 40%; width: 25%; border-radius: 20px; background-color:rgb(21, 105, 111)">
</form>

<br><br>
<div class="">
  <h4 class="mheading">Purchase Entry</h4>
  {% if submitted %}

    Inventry Was Suscessfully Updated!

  {% else %}
<div class="daycare_forms row g-3">

    <form class="" action="" method="POST">
      {% csrf_token %}
      
        {{ form_inventory.as_p }}
     
        <input type="submit" value="Edit Inventory List" class="btn btn-secondary" style="margin-left: 40%; width: 25%; border-radius: 20px; background-color:rgb(21, 105, 111)">
    </form>

</div>
  

  {% endif %}
</div>

<div class="">
  <h4 class="mheading" >Generate New Sales Order Here</h4>
  {% if submitted %}

    Sales Order Was Successfully Created!

  {% else %}
<div class="daycare_forms row g-3" >

    <form class="" action="" method="POST">
      {% csrf_token %}
      
        {{ form.as_p }}
     
        <input type="submit" value="Submit" class="btn btn-secondary" style="margin-left: 40%; width: 25%; border-radius: 20px; background-color:rgb(21, 105, 111)">
    </form>

</div>
  

  {% endif %}
</div>

{% endblock %} 